### ISSUE TITLE
tailwindのフォーマッターをかける

### ISSUE THREAD

**Issue by zEttOn86** [zEttOn86/hugo_theme_windy#25]
- https://qiita.com/ysknsid25/items/da8226d1484307b1b8ea

**Comment by zEttOn86** [comment]
https://github.com/tailwindlabs/prettier-plugin-tailwindcss
を導入したがフォーマット中にエラーが発生。おそらくhugoの文法が含まれているため、フォーマットできないのかも。

- 導入手順
- https://www.npmjs.com/package/prettier-plugin-tailwindcss/v/0.0.0-insiders.d539a72
- https://qiita.com/ysknsid25/items/da8226d1484307b1b8ea

**Comment by zEttOn86** [comment]
- 以下のリポジトリだと使っているみたい
https://github.com/tomowang/hugo-theme-tailwind/blob/6aeb747a630f1d0a184f73a0c616cc795975246f/package.json

**Comment by zEttOn86** [comment]
GitHub Actionsでワークフローの実行順序を制御するためには、以下の方法を使用します。

### 方法1: `needs` キーワードを使用する

`needs` キーワードを使うことで、他のジョブが完了するまで待機し、その後にジョブを実行することができます。これにより、ジョブ間の依存関係を定義できます。

#### 例
以下の例では、`job2` が `job1` の完了を待ってから実行されます。

```yaml
name: Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: echo "Job 1 running"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run job 2
        run: echo "Job 2 running"
```

### 方法2: 同じワークフロー内でのジョブ依存関係の設定

複数のジョブ間の依存関係を設定して、順序を制御することができます。

#### 例
以下の例では、`job3` が `job1` と `job2` の両方の完了を待ってから実行されます。

```yaml
name: Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: echo "Job 1 running"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run job 2
        run: echo "Job 2 running"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Run job 3
        run: echo "Job 3 running"
```

### 方法3: ワークフローのイベントに基づく制御

特定のイベントが発生したときにのみワークフローを実行するように設定できます。

#### 例
以下の例では、`workflow_dispatch` イベントに基づいて手動でワークフローをトリガーします。

```yaml
name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: echo "Job 1 running"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run job 2
        run: echo "Job 2 running"
```

### 方法4: 複数のワークフローの依存関係を設定する

ワークフロー間で依存関係を設定することはできませんが、ワークフローをトリガーする別の方法として、ワークフローの完了イベントを使用して他のワークフローを開始できます。

#### 例
以下の例では、`workflow1` が完了した後に `workflow2` をトリガーします。

```yaml
# .github/workflows/workflow1.yml
name: Workflow 1

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job 1
        run: echo "Workflow 1 running"

# .github/workflows/workflow2.yml
name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run job 2
        run: echo "Workflow 2 running"
```

### まとめ

- **`needs` キーワード** を使うと、ジョブ間の依存関係を定義して順序を制御できます。
- **`workflow_dispatch` イベント** を使うと、手動でワークフローをトリガーできます。
- **`workflow_run` イベント** を使うと、ワークフローの完了をトリガーとして他のワークフローを実行できます。

これらの方法を組み合わせることで、GitHub Actionsで複雑なワークフローの実行順序を制御することができます。
